steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      - build
      - "-f"
      - "Dockerfile.console"
      - "--build-arg"
      - "SCENELOCK_API_BASE=${_API_BASE}"
      - "-t"
      - "${_IMAGE}"
      - "."
images:
  - "${_IMAGE}"
options:
  logging: CLOUD_LOGGING_ONLY
